name: bar_staff_attendance
description: A new Flutter project.
publish_to: none
version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  flutter:       
    sdk: flutter 
  
  # Core UI and responsive design
  sizer: ^2.0.15              
  flutter_svg: ^2.0.9        
  google_fonts: ^4.0.4       # Last Dart 2 compatible version
  shared_preferences: ^2.0.15
  web: ^0.4.0  # Dart 2 compatible version
  
  # Feature dependencies
  cached_network_image: ^3.2.3
  connectivity_plus: ^3.0.3
  dio: ^4.0.6
  fluttertoast: ^8.0.9
  fl_chart: ^0.55.2
  camera: ^0.10.0+4
  permission_handler: ^10.2.0
  mobile_scanner: ^2.0.0
  universal_html: ^2.0.8
  path_provider: ^2.0.14
  flutter_slidable: ^2.0.0
  supabase_flutter: ^1.10.25  # Dart 2 compatible

dev_dependencies:
  flutter_test:
    sdk: flutter   
  flutter_lints: ^2.0.1 

flutter:
  uses-material-design: true 
  assets:
    - assets/
    - assets/images/
